### PR TITLE
Multiple Assignees LGTM Test

### PR DESCRIPTION
**Pull request by sauron-demo-Calvin**
Test

### CODE REVIEW

**Comment by sauron-demo-Calvin** [comment]
:+1:

**Comment by sauron-demo-Josephine** [comment]
:+1:

**Comment by sauron-demo-bbao** [comment]
LGTM

**Comment by jlafleche** [comment]
:star2::sparkles::rocket:
:sparkles::fire::sparkles: **This pull request is queued for merge.**
:fire::sparkles::star2:

Status of Master: N/A

[More Info](http://localhost:8000/sauron-demo/sauron-demo-auto-jlafleche-1477018623/pull/2198)

**Pull request merged**
